# Generated by Django 4.2.14 on 2024-08-13 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='lineons',
            new_name='linenos',
        ),
    ]
